#! /bin/sh
#
# unity-facilitator
#
# Author:	Unity Technologies
#
# chkconfig:    2345 98 02
# description:  A service which facilitates connections between
#               two Unity instances attempting NAT punchthrough.
# processname:  Facilitator
# pidfile:      /opt/unity-facilitator/Facilitator.pid
# config:       /etc/monitrc
#
# ------------------------------------
# Change this to suit your setup

BINARYNAME=Facilitator
HOMEDIR=/opt/unity-facilitator
OPTIONS=""
USERNAME=""

# config where you can define the UNITY_EXTERNAL_IP_x environment variables
if  [ -f /etc/sysconfig/unity-facilitator ] ; then
	.  /etc/sysconfig/unity-facilitator
fi

if [[ $UNITY_EXTERNAL_IP_1 ]]
then
	OPTIONS="-h $UNITY_EXTERNAL_IP_1"
fi

if [[ $UNITY_EXTERNAL_IP_2 ]]
then
	OPTIONS="$OPTIONS -b $UNITY_EXTERNAL_IP_2"
fi

COMMAND="./${BINARYNAME} -d ${OPTIONS}"

# ------------------------------------

RETVAL=0

# See how we were called.
case "$1" in
  start)
	[ -f ${HOMEDIR}/${BINARYNAME}.pid ] && echo $BINARYNAME already running && exit 0
	if [ ! -w /var/lock/subsys/ ]; then 
		echo "Please run as a super user"
		exit 0
	fi

	echo -n "Starting $BINARYNAME: "
	if [[ $USERNAME ]]
	then

	        su $USERNAME -c "cd ${HOMEDIR} && ${COMMAND}"
	else
		cd ${HOMEDIR} && ${COMMAND}
	fi
	RETVAL=$?
        echo
	[ $RETVAL = 0 ] && touch /var/lock/subsys/$BINARYNAME
	;;
  stop)
        echo -n "Stopping $BINARYNAME: "
	cat ${HOMEDIR}/${BINARYNAME}.pid | xargs kill
	RETVAL=$?
        echo
	[ $RETVAL = 0 ] && rm -f /var/lock/subsys/$BINARYNAME
        ;;
  restart)
  	$0 stop
	sleep 5
	$0 start
	RETVAL=$?
	;;
  condrestart)
       [ -e /var/lock/subsys/$BINARYNAME ] && $0 restart
       ;;
  status)
        [ -f ${HOMEDIR}/${BINARYNAME}.pid ] && echo $BINARYNAME is running || echo $BINARYNAME is not running
	RETVAL=$?
	;;
  *)
	echo "Usage: $0 {start|stop|restart|condrestart|status}"
	exit 1
esac

exit $RETVAL
